src/yamllint/README.md, src/yamllint/devcontainer-feature.json, src/yamllint/install.sh, test/yamllint/test.sh
=> add yamllint

CONTRIBUTING.md, README.md
👋 Hello! I'm opening this PR to improve the documentation for the user when they visit this repo. Right now it doesn't look to great if you don't know what this repo is about.
This PR would...
1. Add 2 sections to README.md
2. Add a header image to README.md
3. Add a CONTRIBUTING.md since it is highlighted that this project is looking for contributors
Side-by-side screenshot of the README:
<table>
<thead>
<td>Before
<td>After
<tbody>
<td><img src="https://thum.io/get/https://github.com/devcontainers-contrib/features/blob/main/README.md" />
<td><img src="https://thum.io/get/https://github.com/jcbhmr/devcontainers-contrib-features/blob/better-user-docs/README.md" />
</table>
Todo yet:
=> Better user docs

src/haskell/install.sh
- Temporarily change `HOME` to `_REMOTE_USER_HOME` for the execution of the install script.
- Recursively `chown` back to the `_REMOTE_USER`.
I've also auto-formatted the file, but separated that into a different commit in case you don't want those changes.
The [Haskell feature](https://github.com/devcontainers-contrib/features/tree/main/src/haskell) runs the install such that Cabal, Stack, etc. are installed in `/root` and are not useful when running the dev container in VS Code (or presumably other use cases).
The [GHCup install instructions](https://www.haskell.org/ghcup/install/) mention that the commands should be run as non-root:
> These commands should be run as **non-root/non-admin user**.
The following `.devcontainer.json` illustrates the issue (and is what VS Code creates when …
=> Haskell for non root

src/pulumi/devcontainer-feature.json, src/pulumi/install.sh
**Unsure if the tests pass and if this actually works yet, hence DRAFT**
This will basically wrap the install script in a big `sudo -iu $_REMOTE_USER` block so that it gets executed as the right user.
```sh
sudo -iu "$_REMOTE_USER" <<EOF
...
```
See https://github.com/devcontainers-contrib/features/commit/e3b9039bd2722c40ffa1f848822086c971cf643b
It also bumps the version from 1.0.2 to 1.1.0? Should it bump even farther (i.e. to 2.0.0) since it is a "breaking" change? Is it even a breaking change?
=> Fix pulumi root/non-root user installation

src/typescript/install.sh
There is a typo that printing `node` as `npde`, this PR fixed it.
=> Fix typo in typescript

src/pulumi/install.sh
Fixes #136
In the future it might also be good to add more tests?
=> Fix user account switching issue

src/haskell/devcontainer-feature.json
I believe we need this version bump for the https://github.com/devcontainers-contrib/features/pull/139#event-7920244904 fix to go out to anyone who has already pulled v2 before this PR.
=> Bump version for sudo fix

src/pulumi/devcontainer-feature.json, src/pulumi/install.sh
This is the same as #140, but I made an oopsie and renamed the branch, which closed the #140 PR. My bad!
This PR...
- Adds `pulumi gen-completion bash | sudo tee /etc/bash_completion.d/pulumi > /dev/null`
And hey look! I remembered to bump the version (after being prodded by @fred-asimov to do so, but still 🙂)
=> Use suggestions from @fred-asimov

src/haskell/devcontainer-feature.json, src/haskell/install.sh
I'd like to add another option which I'll do in a separate PR, but with this change the Haskell feature can install an arbitrary list of packages through Haskell to support various VS Code Extensions (see https://github.com/devcontainers-contrib/features/issues/135).
I'm defaulting to no packages, since it adds so much to the build time, but `hlint` is necessary for the linting extension I've mentioned in https://github.com/devcontainers-contrib/features/issues/135.
=> Add the option to install packages like the hlint linter

src/haskell/devcontainer-feature.json, src/haskell/install.sh
While the GHC could be pinned, this provides a way to ensure you have the latest, supported GHC version so that the Haskell Language Server can be programmatically guaranteed to work in a fresh devcontainer config.
I believe that this will fully resolve https://github.com/devcontainers-contrib/features/issues/135
=> Provide a method to ensure HLS will work

src/haskell/devcontainer-feature.json
Sorry! I should've remembered to do this in https://github.com/devcontainers-contrib/features/pull/183.
=> Bump Haskell version for GHC downgrade feature

feature_specs/erlang-asdf.yaml
Note that `erl --version` does not output the Erlang version.
=> Add Erlang via asdf & cookiecutter

src/zig/devcontainer-feature.json, src/zig/install.sh
As Zig is still a young language a large number of projects and libraries target the latest development version.
This patch makes it possible to install the latest development version.
=> add support to zig to install dev builds of zig

src/zsh-plugins/devcontainer-feature.json, src/zsh-plugins/install.sh, test/zsh-plugins/install_plugins.sh, test/zsh-plugins/scenarios.json, test/zsh-plugins/test.sh
Hi, I would like to contribute a feature that I've recently built for my own dev container setup that allows to install (Oh-My-)ZSH plugins from configuration.
Here's the example of how it's intended to be used:
```jsonc
{
"features": {
"ghcr.io/devcontainers/features/common-utils:1": {},
"./zsh-plugins": {
"plugins": "npm zsh-autosuggestions", // <-- zsh plugins go here
"omzPlugins": "https://github.com/zsh-users/zsh-autosuggestions" // <-- oh-my-zsh plugin git urls go here
}
}
}
```
I was trying to follow your contributing guide but it seems outdated as it says to run script from `scripts/` folder to generate a feature but there is no such folder anymore.
So I basically created a feature manually and added a test file which for now does not really test the plugin and I need help with …
=> feat(zsh-plugins): add feature that installs zsh plugins

src/npm-package/install.sh
Tried to use the feature `npm-package:1` but opening in container failed with:
```
Options       :
PACKAGE="wrangler"
VERSION="2.6.2"
===========================================================================
[2022-12-23T10:56:57.516Z] npm
[2022-12-23T10:56:57.516Z]  ERR! code EINVALIDTAGNAME
[2022-12-23T10:56:57.519Z] npm ERR! Invalid tag name "wrangler==2.6.2" of package "wrangler==2.6.2": Tags may not have any characters that encodeURIComponent encodes.
[2022-12-23T10:56:57.521Z] 
npm ERR!
```
I could be doing something wrong but it seems npm install `package-spec` doesn't support the format `PACKAGE==VERSION`.
Quoting https://docs.npmjs.com/cli/v9/commands/npm-install#description 
> A package is:
a) a folder containing a program described by a …
=> Fix package spec by using at symbol.

src/asdf-package/install.sh, src/pipx-package/install.sh
The current pattern matching for Alpine matches any value. The proposed fix matches Alpine specifically for the asdf and pipx features. Formatted out extraneous whitespace from updated files.
Resolves #281
=> fix: improve OS release pattern matching for Alpine

feature_definitions/ansible/feature-definition.json, src/ansible/devcontainer-feature.json
This fixes #301 for ansible.
It could probably be applied to the other packages and produce the desired effect.
=> fix: ansible installAfter version pinning

src/pnpm/dependencies.sh, src/pnpm/devcontainer-feature.json
`pnpm` feature fails to install in Ubuntu images as it is using an old `featmake` version with a known issue.
`featmake v0.0.18` had an issue (see #281) that meant Ubuntu was being incorrectly detected as Alpine, causing feature installations to fail. This was fixed in `v0.0.19` (see #282), and most features were upgraded in #283.
The `pnpm` feature is still using `v0.0.18`. This means it fails to install in an Ubuntu image with the error `apk: command not found`.
This PR bumps the version of `featmake` used in the `pnpm` feature to `0.0.19`. This brings this feature in line with others using `featmake` and solves the install error when using with Ubuntu images.
Feature was failing tests before changes. Verified that `pnpm` feature now passes tests with the following command:
``` …
```
=> fix: pnpm feature - update featmake version to solve alpine misdetection issue

src/elixir-asdf/install.sh
Erlang needs to be installed before Elixir in order to use [default mix commands](https://github.com/asdf-vm/asdf-elixir#default-mix-commands).
=> Reverse order of Elixir and Erlang

src/localstack/devcontainer-feature.json
In order for `localstack start` to work in a devcontainer, it seems to require `docker-in-docker`, so thought it would make sense to be added into the `installsAfter` section of the `devcontainer-feature.json` for `localstack`.
```
vscode@b715ab76b309:/workspaces/features$ devcontainer features test --features localstack
┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
|    Dev Container Features   |   
│           v0.41.0           │
└ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘
>  baseImage:         ubuntu:focal
>  Target Folder:     /workspaces/features
>  features:          localstack
>  workspaceFolder:   /tmp/devcontainercli/container-features-test/1682865791975
⏳ Building test container...
[0 ms] @devcontainers/cli 0.41.0. Node.js v18.16.0. linux 5.15.49-linuxkit arm64.
[1352 ms] [httpOci] Failed to execute …
```
=> Add dind for localstack devcontainer-feature.json installsAfter

src/zsh-plugins/devcontainer-feature.json, src/zsh-plugins/install.sh
There is no need to clone the full Git tree in this situation because we are only interested in the latest commit on the default branch.
This brings a small performance increase.
=> refactor(zsh-plugins): Clone only the latest commit

src/porter/devcontainer-feature.json, src/porter/install.sh, test/porter/install_mixins.sh, test/porter/scenarios.json, test/porter/test.sh
Porter mixin/plugin installation should be optional. If an empty string is submitted in the version field of each mixin, it will not install.
I also found that curl was not installed when running the tests locally.
When testing for the mixins or plugins, you can call the "version" command on each to test if it is installed.
=> Optional install of mixins

src/kubectx-kubens/devcontainer-feature.json, src/kubectx-kubens/install.sh, src/kubectx-kubens/library_scripts.sh, test/kubectx-kubens/test.sh
Hello!
This will fix #459 by installing the Go versions of the tools rather than the shell versions. I also updated this script to use the gh-releases feature and fixed a typo.
=> Update kubectx-kubens to install Go versions (fixes #459)

src/node-asdf/README.md, src/node-asdf/devcontainer-feature.json, src/node-asdf/install.sh, src/node-asdf/library_scripts.sh, test/node-asdf/scenarios.json, test/node-asdf/test.sh
Add new devcontainer feature `node-asdf` to install Node.js via asdf. Resolves #528.
* Add src and test for `node-asdf` feature (taken from `act-asdf`, then adapted)
=> ✨ add new devcontainer feature `node-asdf` to install Node.js via asdf

src/ruby-asdf/README.md, src/ruby-asdf/devcontainer-feature.json, src/ruby-asdf/install.sh, src/ruby-asdf/library_scripts.sh, test/ruby-asdf/scenarios.json, test/ruby-asdf/test.sh
Add new devcontainer feature `ruby-asdf` to install Ruby via asdf. Resolves #526.
* Add src and test for `ruby-asdf` feature (taken from `erlang-asdf`, then adapted)
* apt packages necessary for Ruby development [are taken from](https://github.com/devcontainers/features/blob/main/src/ruby/install.sh#L168-L170) the [Ruby (via rvm)](https://github.com/devcontainers/features/tree/main/src/ruby) devcontainer feature.
=> ✨ add new devcontainer feature `ruby-asdf` to install Ruby via asdf

src/pulumi/install.sh
Currently if any command fails within the non-root user script block the installation will fail silently resulting in `pulumi` not being present in the devcontainer image.
I stumbled into this issue when `get.pulumi.com` was caught by company firewall's SSL filtering, but it was not obvious so I had to dig into what exactly was silently failing.
```
#15 [dev_containers_target_stage 5/6] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=pulumi_0,target=/tmp/build-features-src/pulumi_0     cp -ar /tmp/build-features-src/pulumi_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/pulumi_0  && cd /tmp/dev-container-features/pulumi_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf …
```
=> fix: install script failing silently on inner non-root script erroring

src/sqlfluff/README.md, src/sqlfluff/devcontainer-feature.json, src/sqlfluff/install.sh
I'm are using the `sqlfluff` linter in a [dbt](https://www.getdbt.com/) project. Support for `dbt` in `sqlfluff` is added via the [sqlfluff-templater-dbt](https://pypi.org/project/sqlfluff-templater-dbt/) plugin which needs to be installed alongside `sqlfluff`.
Extend the `sqlfluff` feature to support an optional `plugins` option that can pass a space separated list of plugins to be installed.
Example:
```json
{
"features": {
"ghcr.io/devcontainers-contrib/features/sqlfluff:1": {
"version": "latest",
"plugins": "sqlfluff-templater-dbt==2.3.5"
}
}
}
```
First time contributing to this project - feel free to let me know if there's anything else I need/should add
=> Extend the sqlfluff feature to support the injection of sqlfluff plugins

src/gh-release/devcontainer-feature.json, src/gh-release/install.sh, test/gh-release/scenarios.json, test/gh-release/test_no_git.sh
gh-release requires git as part of the install process
=>  gh-release requires git as part of the install process
