devcontainers-contrib/features

src/pulumi/devcontainer-feature.json
src/pulumi/install.sh

clean up and add additional standard convensions as seen in built-it features

4-suggestion-clean-up-apt-cache

---

src/kubectx-kubens/devcontainer-feature.json
src/kubectx-kubens/install.sh
test/kubectx-kubens/test.sh

feat: added Kubectx and Kubens feature

---

.devcontainer/devcontainer.json
.github/workflows/test.yaml
src/argo-workflows/devcontainer-feature.json
src/argo-workflows/install.sh
test/argo-workflows/test.sh

feat: Argo Workflows Feature

---

src/digitalocean-cli/devcontainer-feature.json
src/digitalocean-cli/install.sh
test/digitalocean-cli/test.sh

feat: Issue DigitalOcean CLI feature

---

.github/workflows/test.yaml
src/heroku-cli/devcontainer-feature.json
src/heroku-cli/install.sh
test/heroku-cli/test.sh

feat: Heroku CLI feature

---

.devcontainer/devcontainer.json
.github/workflows/test.yaml
src/poetry/devcontainer-feature.json
src/poetry/install.sh
test/poetry/test.sh

Poetry feature

---

.github/workflows/test.yaml
src/datasette/devcontainer-feature.json
src/datasette/install.sh
src/jrnl/devcontainer-feature.json
src/jrnl/install.sh
src/lektor/devcontainer-feature.json
src/lektor/install.sh
src/localstack/devcontainer-feature.json
src/localstack/install.sh
src/meltano/devcontainer-feature.json
src/meltano/install.sh
src/mitmproxy/devcontainer-feature.json
src/mitmproxy/install.sh
src/mkdocs/devcontainer-feature.json
src/mkdocs/install.sh
src/pdm/devcontainer-feature.json
src/pdm/install.sh
src/pyscaffold/devcontainer-feature.json
src/pyscaffold/install.sh
test/datasette/test.sh
test/jrnl/test.sh
test/lektor/test.sh
test/localstack/test.sh
test/meltano/test.sh
test/mitmproxy/test.sh
test/mkdocs/test.sh
test/pdm/test.sh
test/pyscaffold/test.sh

pipx based features of popular cli utilities

---

src/ansible/devcontainer-feature.json
src/ansible/install.sh

add feature to install ansible-collections if variable is defined

---

src/flit/devcontainer-feature.json
src/flit/install.sh
src/pyinfra/devcontainer-feature.json
src/pyinfra/install.sh
src/qrcode/devcontainer-feature.json
src/qrcode/install.sh
src/twine/devcontainer-feature.json
src/twine/install.sh
src/youtube-dl/devcontainer-feature.json
src/youtube-dl/install.sh
src/yt-dlp/devcontainer-feature.json
src/yt-dlp/install.sh
test/flit/test.sh
test/pyinfra/test.sh
test/qrcode/test.sh
test/twine/test.sh
test/youtube-dl/test.sh
test/yt-dlp/test.sh

Multiple missing features

---

.github/actions/list-folder-action/action.yaml
.github/workflows/linter-automated.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

migrated all checkout actions to v3 (node 16 based) 
also replaced set_output usage in feature discovery action to set env

fix warnings

---

CONTRIBUTING.md

@jcbhmr -- I see that you're working on this sort of documentation in https://github.com/devcontainers-contrib/features/pull/95, so feel free to close, cut-and-paste, etc. I thought I'd just share what I was going to propose given what I learned while figuring out things for myself.

Add contributor instructions for running a test locally

---

src/pulumi/devcontainer-feature.json

This should make it actually publish a new version like https://github.com/devcontainers-contrib/features/issues/136#issuecomment-1331196744
Signed-off-by: Jacob Hummer <jcbhmr@outlook.com>

Bump version from 1.1.0 to 1.2.0

---

CONTRIBUTING.md

Add a proper security email

---

src/pipx-package/devcontainer-feature.json
src/pipx-package/install.sh

pipx packagae installs python even when not required

---

src/asdf-package/devcontainer-feature.json
test/asdf-package/install_act_with_repo.sh
test/asdf-package/scenarios.json

asdf-package missing pluginRepo option

---

src/zsh-plugins/devcontainer-feature.json
src/zsh-plugins/install.sh
test/zsh-plugins/multiple-omz-plugins.sh
test/zsh-plugins/scenarios.json

thanks @nandordudas
Fixes #247

ZSH Plugins are installed incorrectly

---

src/homebrew-package/devcontainer-feature.json
src/homebrew-package/install.sh
test/homebrew-package/scenarios.json
test/homebrew-package/test.sh
test/homebrew-package/test_git_based_version.sh
test/homebrew-package/test_latest.sh
test/homebrew-package/test_specific_version.sh

Homebrew package feature

---

README.md

Signed-off-by: Giuseppe Romagnuolo <gromag@users.noreply.github.com>

Minor misspellings

---

src/asdf-package/devcontainer-feature.json
src/asdf-package/install.sh

Asdf features are not installing if asdf happened to be installed in the system

---

src/homebrew-package/devcontainer-feature.json
src/homebrew-package/install.sh

HomeBrew-Package creates a .gitconfig file and thus breaks devcontainer copy of this file.

---

src/postgres-asdf/README.md
src/postgres-asdf/devcontainer-feature.json
src/postgres-asdf/install.sh
src/postgres-asdf/library_scripts.sh
test/postgres-asdf/scenarios.json
test/postgres-asdf/test.sh

Wanted to add PostgreSQL (via asdf) as a feature. Nothing too sophisticated here, just copied the erlang-asdf feature (including tests) and changed where necessary, including adding the prereqs [specified here](https://github.com/smashedtoatoms/asdf-postgres). I initially had linux-headers in there but the build failed so I removed it. I'm not sure if you want this to be 1.0 or not; feel free to change whatever.

Add PostgreSQL (via asdf)

---

src/actionlint/README.md
src/actionlint/devcontainer-feature.json
src/actionlint/install.sh
src/actionlint/library_scripts.sh

Hello,
This adds [actionlint](https://github.com/rhysd/actionlint) to the features, a linter for GitHub Actions.

feat: add actionlint feature

---

src/localstack/devcontainer-feature.json
src/localstack/install.sh

feat: pipx includeDeps option (#399)

---

src/gh-release/devcontainer-feature.json
src/gh-release/install.sh

gh-release (#407) (#408)

---

src/age/README.md
src/age/devcontainer-feature.json

This will fix the name of the feature age from mkcert.

Fix age name from mkcert

---

src/localstack/devcontainer-feature.json
src/localstack/install.sh
test/localstack/scenarios.json
test/localstack/test_with_python_feature.sh

Fixes #421
installs a 3.10.8 python side by side with any existing python installation

[Bug]: Localstack Conflicing With Python DevContainer Feature

---

src/zsh-plugins/devcontainer-feature.json
src/zsh-plugins/install.sh
test/zsh-plugins/install_plugins_on_plain_ubuntu.sh
test/zsh-plugins/scenarios.json

[Bug]: ZSH fails to install

---

src/porter/README.md
src/porter/devcontainer-feature.json
src/porter/install.sh
src/porter/library_scripts.sh
test/porter/scenarios.json
test/porter/test.sh

[Feature Request]: Porter

---

src/cz-cli/README.md
src/cz-cli/devcontainer-feature.json
src/cz-cli/install.sh
src/cz-cli/library_scripts.sh
test/cz-cli/scenarios.json
test/cz-cli/test.sh

Hope to support the cz-cli feature

---

src/prettier/README.md
src/prettier/devcontainer-feature.json
src/prettier/install.sh
src/prettier/library_scripts.sh
test/prettier/scenarios.json
test/prettier/test.sh

Addresses https://github.com/devcontainers-contrib/features/issues/448

Add prettier

---

src/markdownlint-cli/README.md
src/markdownlint-cli/devcontainer-feature.json
src/markdownlint-cli/install.sh
src/markdownlint-cli/library_scripts.sh
test/markdownlint-cli/scenarios.json
test/markdownlint-cli/test.sh

Partially fixes https://github.com/devcontainers-contrib/features/issues/445

Add markdownlint-cli

---

src/markdownlint-cli2/README.md
src/markdownlint-cli2/devcontainer-feature.json
src/markdownlint-cli2/install.sh
src/markdownlint-cli2/library_scripts.sh
test/markdownlint-cli2/scenarios.json
test/markdownlint-cli2/test.sh

Partially fixes https://github.com/devcontainers-contrib/features/issues/445

Add markdownlint-cli2

---

src/sqlfluff/README.md
src/sqlfluff/devcontainer-feature.json
src/sqlfluff/install.sh
src/sqlfluff/library_scripts.sh
test/sqlfluff/scenarios.json
test/sqlfluff/test.sh

Add sqlfluff feature

---

src/rabbitmq-asdf/README.md
src/rabbitmq-asdf/devcontainer-feature.json
test/asdf-package/scenarios.json

Rabbitmq feature failes on latest version

---

src/auditjs/devcontainer-feature.json
src/auditjs/install.sh

Bug: Typo in auditjs installAfter value

---

src/gh-release/devcontainer-feature.json
src/gh-release/install.sh
src/gh-release/library_scripts.sh

New nanolayer version for gh-release feature

---

src/gh-release/devcontainer-feature.json
src/gh-release/install.sh

update gh-release (#519)

---

.devcontainer/devcontainer.json

Keep `devcontainer.json` up to date.
* Upgrade some devcontainer features to their latest version

⬆️ Upgrade devcontainer feature versions

---

src/gleam/README.md
src/gleam/devcontainer-feature.json
src/gleam/install.sh
src/gleam/library_scripts.sh
test/gleam/scenarios.json
test/gleam/test_defaults_debian.sh

[Feature Request]: Gleam CLI

---

src/composer/README.md
src/composer/devcontainer-feature.json
src/composer/install.sh
src/composer/library_scripts.sh
test/composer/scenarios.json
test/composer/test_defaults_debian.sh

Add new devcontainer feature  to install [Composer](https://getcomposer.org/) via GitHub releases.

✨️ Add new devcontainer feature `composer` via GitHub releases

---

src/vscode-server/README.md
src/vscode-server/devcontainer-feature.json
src/vscode-server/install.sh
src/vscode-server/library_scripts.sh
test/vscode-server/scenarios.json
test/vscode-server/test.sh

Add vscode-server

---

src/vscode-cli/README.md
src/vscode-cli/devcontainer-feature.json
src/vscode-cli/install.sh
src/vscode-cli/library_scripts.sh
test/vscode-cli/scenarios.json
test/vscode-cli/test.sh

Add vscode-cli
